%Doctor.Config{
  ignore_modules: [
    Plotto.Axis,
    Plotto.CandlestickData,
    Plotto.Chart.Builder,
    Plotto.Data,
    Plotto.Font.DejaVuSans,
    Plotto.Font.Glyph,
    Plotto.Font.TrueType,
    Plotto.LineData,
    Plotto.Options,
    Plotto.PNG.Canvas,
    Plotto.PNG.Color,
    Plotto.PNG.Encoder,
    Plotto.PNG.Rasterizer,
    Plotto.SVG.Element,
    Plotto.SVG.Renderer,
    Plotto.SVG.Renderer.BarChart,
    Plotto.SVG.Renderer.CandlestickChart,
    Plotto.SVG.Renderer.LineChart,
    Plotto.SVG.Renderer.Shared,
    Plotto.SVG.Serializer,
    Plotto.Theme
  ],
  ignore_paths: [],
  min_module_doc_coverage: 100,
  min_module_spec_coverage: 100,
  min_overall_doc_coverage: 100,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 100,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false,
  failed: false
}